logging:
  level:
    org.springframework: INFO
    com.scwot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

app:
  input: "/Volumes/BLACK/- to-rename/!ready-test"
  destination: "/Volumes/BLACK/- renamed"

server:
  port: 8080
