logging:
  level:
    org.springframework: ERROR
    com.scwot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"


app:
  input: "E:\\Music\\!incoming\\!renamer_testing_input"
  destination: "E:\\Music\\!incoming\\!renamer_testing_output"
