logging:
  level:
    org.springframework: ERROR
    com.scwot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"


app:
  input: "nfs://localhost//!to-rename/!ready-test"
  destination: "nfs://localhost//!to-rename/!renamed"
  input2: "/Users/user/.mounty/BLACK/!to-rename/!ready-test"
  destination2: "/Users/user/.mounty/BLACK/!to-rename/!renamed"
